<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyPatternHunter.Domain\SkyPatternHunter.Domain.csproj" />
    <ProjectReference Include="..\SkyPatternHunter.Application\SkyPatternHunter.Application.csproj" />
    <ProjectReference Include="..\SkyPatternHunter.Infrastructure\SkyPatternHunter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
